### ISSUE TITLE
Grab stuff off Github

### ISSUE THREAD

**Issue by Miladiir** [LiquidFenrir/MultiUpdater#1]
removed.

**Comment by LiquidFenrir** [comment]
Concerning ftpd, you can always get the latest cia at http://mtheall.com/~mtheall/ftpd.cia
But yes, I'll be adding this features for applications that don't have a nightlies site

**Comment by ksanislo** [comment]
You'll probably have better luck getting a list of .cias to update from [TitleDB](https://titledb.com), which tracks github as well as non-github files or files in .zip archives... View source on the website for details on how the API works, and look for changes in the mtime field to tell if a .cia has been updated since a previous scan.

**Comment by Hikari-chan** [comment]
There's no easy way to do this; unlike the examples in config.json, Github repos/releases don't have a direct URL to download the latest package; it differs by repository and would likely need to be manually updated every time a new release is made.
